# .github/workflows/release.yml

name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    # ⬇️ ADD THIS PERMISSIONS BLOCK ⬇️
    # This grants the GITHUB_TOKEN write permissions for repository contents,
    # which is required to create a release.
    permissions:
      contents: write

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v -o wacinv-${{ matrix.goos }}-${{ matrix.goarch }} ./...
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          body: "This is an automated release."
          files: wacinv-${{ matrix.goos }}-${{ matrix.goarch }}
